# numpy

In [9]:
#IMPORT NUMPY LIBARAY
import numpy as np
from numpy import random

In [10]:
#create simple array from the list
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [11]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr.ndim

2

In [13]:
arr.shape #shape of array

(2, 4)

In [14]:
type(arr)

numpy.ndarray

In [15]:
arr.data#memory locaTION

# RANDOM NUMBER GENERATOR USING NP

In [16]:
x=random. randint(1000)
x

182

In [17]:
x=random. rand(1000)
x

array([3.86631098e-01, 2.62269532e-01, 5.23237427e-01, 6.32653321e-01,
       2.61184248e-01, 8.64599042e-01, 3.68507211e-01, 6.40321550e-01,
       4.71158063e-01, 9.50991865e-01, 9.00344410e-01, 8.07897679e-01,
       1.03613631e-01, 3.83038157e-01, 1.48351535e-01, 5.61267725e-01,
       5.19258628e-01, 8.41143490e-01, 7.27463240e-01, 7.56419728e-01,
       3.04706864e-01, 4.24055247e-01, 5.66265146e-01, 2.13645993e-01,
       4.12765239e-01, 2.45191251e-01, 5.23333326e-01, 4.64435184e-01,
       4.05924637e-03, 2.25353813e-01, 9.02463196e-01, 8.68109467e-02,
       6.73127204e-01, 3.86064502e-01, 5.03777732e-01, 6.45028798e-01,
       1.19514263e-01, 9.60807171e-01, 6.01035897e-01, 1.28604099e-01,
       5.55457338e-01, 7.31721777e-01, 8.22964874e-01, 7.02657054e-01,
       2.27958770e-02, 7.42609767e-01, 4.50731135e-01, 9.28360315e-01,
       5.69197890e-01, 2.06150290e-01, 6.96427179e-01, 5.92345015e-01,
       2.78141302e-01, 7.60646597e-01, 9.22489287e-01, 2.98876530e-01,
      

In [18]:
x=random. randint(1000,size=(5,2)) #multiple direction random array
x

array([[903, 313],
       [292, 658],
       [529, 238],
       [755, 848],
       [ 46, 692]])

In [19]:
#a=1D ARRAY ,with 7integer
#b=1D ARRAY ,with 7integer
#math operation

In [20]:
a=random. randint(1000,size=(7))
a

array([ 24, 211, 157, 973, 176, 134, 968])

In [21]:
b=random. randint(1000,size=(7))
b

array([ 76, 704, 835,  73, 340,  79, 547])

In [22]:
a+b

array([ 100,  915,  992, 1046,  516,  213, 1515])

In [23]:
a-b

array([ -52, -493, -678,  900, -164,   55,  421])

In [24]:
a/b

array([ 0.31578947,  0.29971591,  0.18802395, 13.32876712,  0.51764706,
        1.69620253,  1.76965265])

In [25]:
a**b

array([         0, -981871871, -196963899,   76413037,          0,
                0,          0], dtype=int32)

In [26]:
a*b

array([  1824, 148544, 131095,  71029,  59840,  10586, 529496])

In [27]:
a//b

array([ 0,  0,  0, 13,  0,  1,  1], dtype=int32)

# matrix in number

In [34]:
a=np.matrix('1,2; 3,4')
a            

matrix([[1, 2],
        [3, 4]])

In [36]:
b=np.matrix([[5,6,7],[4,6,6]])
b            

matrix([[5, 6, 7],
        [4, 6, 6]])

In [40]:
arr = np.array([[1,23,78],[98,68,54],[79,43,46]])
arr

array([[ 1, 23, 78],
       [98, 68, 54],
       [79, 43, 46]])

In [41]:
np.amin(arr)

1

In [42]:
np.amax(arr)

98

In [43]:
np.mean(arr)

54.44444444444444

In [45]:
np.median(arr)

54.0

In [46]:
np.std(arr)

28.453123675856403

In [47]:
np.var(arr)

809.5802469135803